<<<<<<< HEAD
name: Launcher Bootstrapper
=======
name: Asylum Bootstrapper
>>>>>>> ce1e96f84b6a9a051cb587b35261fe3274801de9

on:
  push:
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Asylum App
      run: go build -o AsylumApp.exe -ldflags -H=windowsgui -v ./... 

    - name: Upload Build Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: AsylumApp-${{ matrix.os }}
        path: ./AsylumApp.exe
